name: Build Prospector Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Cache west modules
      uses: actions/cache@v4
      with:
        path:  < /dev/null | 
          modules/
          tools/
          zephyr/
          bootloader/
          zmk/
        key: ${{ runner.os }}-build-${{ hashFiles(**/west.yml) }}
        restore-keys: |
          ${{ runner.os }}-build-
          
    - name: West Init
      run: west init -l config
      
    - name: West Update
      run: west update
      
    - name: West Zephyr Export
      run: west zephyr-export
      
    - name: West Build (Prospector Scanner)
      run: west build -s zmk/app -b seeeduino_xiao_ble -- -DSHIELD=prospector_scanner -DZMK_CONFIG="$GITHUB_WORKSPACE/config"
      
    - name: Upload Scanner Firmware
      uses: actions/upload-artifact@v4
      with:
        name: prospector-scanner-firmware
        path: build/zephyr/zmk.uf2
        
    - name: West Build (Prospector Adapter - Original Dongle)
      run: west build -s zmk/app -b seeeduino_xiao_ble -d build-adapter -- -DSHIELD=prospector_adapter -DZMK_CONFIG="$GITHUB_WORKSPACE/config"
      
    - name: Upload Adapter Firmware  
      uses: actions/upload-artifact@v4
      with:
        name: prospector-adapter-firmware
        path: build-adapter/zephyr/zmk.uf2
